#!/usr/bin/env python3
"""Skill: code-review-report - Generate a code review report from a spec."""

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional


def load_spec(spec_path: str) -> Dict[str, Any]:
    """Load and parse a JSON spec file."""
    path = Path(spec_path)
    if not path.exists():
        raise FileNotFoundError(f"Spec file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def match_trigger(spec: Dict[str, Any], trigger: str) -> bool:
    """Check if the trigger matches the spec's trigger condition."""
    spec_trigger = spec.get("trigger", "")
    return spec_trigger == trigger


def generate_report(spec: Dict[str, Any]) -> str:
    """Generate a simple markdown report from the spec."""
    lines = []
    lines.append(f"# Code Review Report: {spec.get('name', 'Untitled')}")
    lines.append("")
    lines.append(f"**Trigger:** {spec.get('trigger', 'N/A')}")
    lines.append("")
    lines.append("## Files to Review")
    files = spec.get("files", [])
    if files:
        for f in files:
            lines.append(f"- {f}")
    else:
        lines.append("- No files specified")
    lines.append("")
    lines.append("## Rules")
    rules = spec.get("rules", [])
    if rules:
        for r in rules:
            lines.append(f"- {r}")
    else:
        lines.append("- No rules specified")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by code-review-report skill*")
    return "\n".join(lines)


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a code review report from a spec.")
    parser.add_argument("spec", help="Path to the JSON spec file")
    parser.add_argument("--trigger", default="", help="Trigger string to match")
    parser.add_argument("--output", "-o", help="Output file path (default: stdout)")
    args = parser.parse_args(argv)

    try:
        spec = load_spec(args.spec)
    except Exception as e:
        print(f"Error loading spec: {e}", file=sys.stderr)
        return 1

    if args.trigger and not match_trigger(spec, args.trigger):
        print(f"Trigger mismatch: spec trigger '{spec.get('trigger', '')}' != '{args.trigger}'", file=sys.stderr)
        return 1

    report = generate_report(spec)

    if args.output:
        output_path = Path(args.output)
        try:
            output_path.write_text(report, encoding="utf-8")
        except Exception as e:
            print(f"Error writing output: {e}", file=sys.stderr)
            return 1
    else:
        print(report)

    return 0


def selftest() -> int:
    """Run a self-test to verify the skill works correctly."""
    print("运行自检...")
    try:
        # Create a temporary directory and spec file
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = Path(tmpdir)
            spec_file = tmp_path / "spec.json"
            spec_data = {
                "name": "Test Review",
                "trigger": "test-trigger",
                "files": ["src/main.py", "src/utils.py"],
                "rules": ["Use type hints", "No global variables"]
            }
            spec_file.write_text(json.dumps(spec_data), encoding="utf-8")

            # Test load_spec
            spec = load_spec(str(spec_file))
            assert spec["name"] == "Test Review", "Spec name mismatch"

            # Test match_trigger
            assert match_trigger(spec, "test-trigger") is True, "Trigger should match"
            assert match_trigger(spec, "wrong-trigger") is False, "Trigger should not match"

            # Test generate_report
            report = generate_report(spec)
            assert "Test Review" in report, "Report missing name"
            assert "src/main.py" in report, "Report missing file"
            assert "Use type hints" in report, "Report missing rule"

            # Test main with output file
            output_file = tmp_path / "report.md"
            ret = main([str(spec_file), "--trigger", "test-trigger", "--output", str(output_file)])
            assert ret == 0, f"main returned {ret}"
            assert output_file.exists(), "Output file not created"
            content = output_file.read_text(encoding="utf-8")
            assert "Test Review" in content, "Output file missing report content"

            # Test main with stdout (no output file)
            ret = main([str(spec_file), "--trigger", "test-trigger"])
            assert ret == 0, f"main stdout returned {ret}"

            # Test main with trigger mismatch
            ret = main([str(spec_file), "--trigger", "wrong"])
            assert ret == 1, f"Trigger mismatch should return 1, got {ret}"

        print("自检通过")
        return 0
    except Exception as e:
        print(f"自检失败: {e}")
        return 1


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    else:
        sys.exit(main())
